spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    commit.interval.ms: 1000
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings:
  process-in-0.destination: bank
  process-out-0.destination: customer
  process-out-1.destination: customer-details
  process-out-2.destination: account
  process-out-3.destination: account-connect
  process-out-4.destination: transaction
  process-out-5.destination: atm-transaction
  process-out-6.destination: auto-transaction
  process-out-7.destination: transfer-transaction
spring.application.name: bank-branching